services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
    networks:
      - billing-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U billing -d billing_db']
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@billing.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8081:80'
    networks:
      - billing-network
    depends_on:
      - postgres

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   restart: unless-stopped
  #   environment:
  #     RABBITMQ_DEFAULT_USER: billing
  #     RABBITMQ_DEFAULT_PASS: billing
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   ports:
  #     - '5673:5672'
  #     - '15673:15672'
  #   networks:
  #     - billing-network
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  billing-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: billing
      DB_PASSWORD: billing
      DB_DATABASE: billing_db

      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672/
      APP_NAME: billing-service
      RABBITMQ_FANOUT_EXCHANGE: fanout_exchange
      RABBITMQ_HEARTBEAT_INTERVAL: 30
      RABBITMQ_DIRECT_EXCHANGE: billing_direct_exchange
      RABBITMQ_PRIMARY_QUEUE: order-bill-ship_primary_queue
      RABBITMQ_RETRY_QUEUE: billing_retry_queue
      RABBITMQ_RETRY_BINDING_KEY: billing_retry_key
      RABBITMQ_ERROR_BINDING_KEY: billing_error_key
      FAILED_MESSAGE_DELAYED_RETRIES: 5
      FAILED_MESSAGE_IMMEDIATE_RETRIES: 3
      RETRY_QUEUE_MESSAGE_TTL: 60000
      CONSUME_MESSAGE_LIMIT: 100
      DISPATCH_MESSAGE_LIMIT: 100

      PORT: 3000
      NODE_ENV: development
    ports:
      - '3001:3000'
    networks:
      - billing-network
      - sales-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - .:/app
      - /app/node_modules

networks:
  billing-network:
    driver: bridge
  sales-network:
    external: true
    name: sales_sales-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  rabbitmq_data:
    driver: local
